central/urls.py
from django.urls import path
from .views import homepage_central

urlpatterns = [
    path('', homepage_central, name="home-central"),

]

get_seeded/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from votingManager.views import votingPage_VM


urlpatterns = [
    path("",include("central.urls")),

    path("getseededteam/",include("getSeededTeam.urls")),
    path("getseededteam/votingManager/",include("votingManager.urls")),
    path('admin/', admin.site.urls),

    path("votingPage/", votingPage_VM, name="votingPage-getSeeded"),# in votingManager
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

votingManager/forms.py
from django import forms
from getSeededTeam.models import Candidate


class AddVoteCodes(forms.Form):
    number = forms.NumberInput()



class DeleteVoteCodes(forms.Form):
    code = forms.CharField(max_length=20)

templates/extras/base_2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'central/main.css' %}">

    {% if title %}
    <title>Django Blog - {{ title }}</title>
    {% else %}
    <title>Django Blog</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="#">Django Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="#">Home</a>
                    <a class="nav-item nav-link" href="#">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="#">New Post</a>
                    <a class="nav-item nav-link" href="#">Profile</a>
                    <a class="nav-item nav-link" href="#">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="#">Login</a>
                    <a class="nav-item nav-link" href="#">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/extras/blank_blog.html
{% extends "base.html" %}


{% block body %}

<!-- Image and text style="background-color: #e3f2fd;-->
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} m-3 p-2">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}

            <div class="container">
                {% block content %}                    {% endblock %}
            </div>

        </div>
    </div>
</main>




{% endblock %}

templates/extras/navbarmain.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light mb-3" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="#">
        <img src="{% static 'central/favicon.ico' %}" width="40" height="40" class="d-inline-block align-top rounded" alt="" loading="lazy">
    </a>
    <a class="navbar-brand" href="#">Get Seeded</a>
    <!--    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
    <!--        <span class="navbar-toggler-icon"></span>-->
    <!--    </button>   <span class="sr-only">(current)</span>   -->

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
                <a class="nav-link" href="#">Home </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-md-auto">

            <li class="nav-item px-2 ">
                <a class="nav-link" href="#">login </a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link" href="#">lll</a>
            </li>
        </ul>
    </div>
</nav>

templates/extras/test.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="#">
        <img src="{% static 'central/favicon.ico' %}" width="40" height="40" class="d-inline-block align-top rounded" alt="" loading="lazy">
    </a>
    <a class="navbar-brand" href="#">Get Seeded</a>
<!--    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--    </button>   <span class="sr-only">(current)</span>   -->

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
                <a class="nav-link" href="#">Home </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-md-auto">

            <li class="nav-item px-2 ">
                <a class="nav-link" href="#">login </a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link" href="#">lll</a>
            </li>
        </ul>
    </div>
</nav>


<h1>Hello, world!</h1>


<tr><th><label for="id_tech">select a candidate for Technology:</label></th><td><select name="tech" id="id_tech">
</select></td></tr>
<tr><th><label for="id_gen">select a candidate for General:</label></th><td><select name="gen" id="id_gen">
</select></td></tr>
<tr><th><label for="id_soc">select a candidate for Social:</label></th><td><select name="soc" id="id_soc">
</select></td></tr>
<tr><th><label for="id_code">Vote Code:</label></th><td><input type="text" name="code" maxlength="20" required id="id_code"></td></tr>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>